title:         'purpleKarrot'
tagline:       'Gedankenexperimente'
url:           'http://purplekarrot.net'

author:        'Daniel Pfeifer'
copyright:     '2024'

email:         'daniel@pfeifer-mail.de'
github:        'https://github.com/purplekarrot'
linkedin:      'https://linkedin.com/in/purplekarrot'

paginate:      30
paginate_path: '/index:num.html'
permalink:     '/blog/:title.html'
include:       ['.well-known']

sass:
  style:       :compact

plugins:
  - jekyll-feed
